### PR TITLE
Test with more versions of SageMath

### PR DESCRIPTION
**Pull request by saraedum**
and optional dependencies

##### Dependencies

* [x] https://github.com/conda-forge/e-antic-feedstock/pull/52

### CODE REVIEW

**Comment by saraedum** [comment]
Needs https://github.com/conda-forge/cpycppyy-feedstock/pull/43.

**Comment by saraedum** [comment]
@videlec apart from some warnings that I can take care of there are also a few actual doctest errors.

**Comment by videlec** [comment]
It is `flipper` (via `realalg`). Maybe we could isolate more the flipper imports.

**Comment by saraedum** [comment]
> It is `flipper` (via `realalg`) which is the cause of warnings. Maybe we could isolate more the flipper imports.

If flipper isn't used that much, it's a good idea anyway. Otherwise, we should just fix realalg maybe?

**Comment by saraedum** [comment]
There's already a PR actually https://github.com/MarkCBell/realalg/pull/6

**Pull request merged**
