### PR TITLE
implement geometric automaton

### PR DESCRIPTION
**Pull request by videlec**
Implement a generic version of automaton and add the following ones
* flip graph of (topological) triangulations
* geometric automaton
* geometric automaton with linear constraint

### CODE REVIEW

**Comment by videlec** [comment]
@saraedum In this branch, I implemented something to check that a given candidate `GL2ROrbitClosure` is indeed something closed. It is somehow a higher dimensional code of your iso-Delaunay tesselation that works with L^oo-Delaunay rather than L^2-Delaunay. Theoretically, we could make it for the (3, 4, 13) triangle... however sage polytopes are damnfully slow :-(
```
sage: import veerer.linear_family
sage: f = veerer.linear_family.VeeringTriangulationLinearFamilies.triangle_3_4_13_unfolding_orbit_closure()
sage: A = f.geometric_automaton(run=False) # long time
sage: A.run(20) # very long time
```
Here the polytopes are cones of dimension 4 (the dimension of the manifold) in ambient dimension 48 and defined over Q[sqrt(5)].

**Comment by videlec** [comment]
> @saraedum In this branch, I implemented something to check that a given candidate `GL2ROrbitClosure` is indeed something closed. It is somehow a higher dimensional code of your iso-Delaunay tesselation that works with L^oo-Delaunay rather than L^2-Delaunay. Theoretically, we could make it for the (3, 4, 13) triangle... however sage polytopes are damnfully slow :-(
> 
> ```
> sage: import veerer.linear_family
> sage: f = veerer.linear_family.VeeringTriangulationLinearFamilies.triangle_3_4_13_unfolding_orbit_closure()
> sage: A = f.geometric_automaton(run=False) # long time
> sage: A.run(20) # very long time
> ```
> 
> Here the polytopes are cones of dimension 4 (the dimension of the manifold) in ambient dimension 48 and defined over Q[sqrt(5)].

Much better with normaliz! I already computed > 1500 cells whereas sage was stuck after 5 of them.

**Comment by saraedum** [comment]
I could try to speed this up a bit further. Maybe that's something we can discuss on Friday.

**Comment by saraedum** [comment]
With your sample code I get a ValueError.

<details>
<pre>
ValueError                                Traceback (most recent call last)
Cell In[3], line 3
      1 import veerer.linear_family
      2 f = veerer.linear_family.VeeringTriangulationLinearFamilies.triangle_3_4_13_unfolding_orbit_closure()
----> 3 A = f.geometric_automaton(run=False) # long time

File ~/proj/eskin/veerer/veerer/linear_family.py:611, in VeeringTriangulationLinearFamily.geometric_automaton(self, run, backend)
    609 from .automaton import GeometricAutomatonSubspace
    610 A = GeometricAutomatonSubspace(backend=backend)
--> 611 A.set_seed(self)
    612 if run:
    613     A.run()

File ~/proj/eskin/veerer/veerer/automaton.py:498, in Automaton.set_seed(self, state)
    495 if self._state is not None:
    496     raise ValueError('seed already set')
--> 498 state = self._seed_setup(state)
    500 # TODO: check to be removed
    501 if env.CHECK:

File ~/proj/eskin/veerer/veerer/automaton.py:934, in GeometricAutomatonSubspace._seed_setup(self, state)
    933 def _seed_setup(self, state):
--> 934     if not isinstance(state, VeeringTriangulationLinearFamily) or not state.is_geometric(backend=self._backend):
    935         raise ValueError('invalid seed')
    936     state = state.copy(mutable=True)

File ~/proj/eskin/veerer/veerer/veering_triangulation.py:3232, in VeeringTriangulation.is_geometric(self, backend)
   3209 r"""
   3210 Test whether this coloured triangulation is geometric.
   3211
   (...)
   3229     True
   3230 """
   3231 dim = self.dimension()
-> 3232 P = self.geometric_polytope(backend=backend)
   3233 Pdim = P.affine_dimension()
   3234 assert Pdim <= 2 * dim

File ~/proj/eskin/veerer/veerer/linear_family.py:606, in VeeringTriangulationLinearFamily.geometric_polytope(self, x_low_bound, y_low_bound, hw_bound, backend)
    604 self._set_subspace_constraints(cs.insert, y, HORIZONTAL)
    605 self._set_geometric_constraints(cs.insert, x, y, hw_bound=hw_bound)
--> 606 return cs.cone(backend)

File ~/proj/eskin/veerer/veerer/linear_expression.py:458, in ConstraintSystem.cone(self, backend)
    456 if backend == 'ppl':
    457     import ppl
--> 458     return Cone_ppl(QQ, ppl.C_Polyhedron(self.ppl()))
    459 elif backend == 'sage':
    460     from sage.geometry.polyhedron.constructor import Polyhedron

File ~/proj/eskin/veerer/veerer/linear_expression.py:350, in ConstraintSystem.ppl(self)
    348 cs = ppl.Constraint_System()
    349 for constraint in self._data:
--> 350     cs.insert(constraint.ppl())
    351 return cs

File ~/proj/eskin/veerer/veerer/linear_expression.py:292, in LinearConstraint.ppl(self)
    290     return self._expression.ppl() > 0
    291 elif self._op == op_GE:
--> 292     return self._expression.ppl() >= 0

File ~/proj/eskin/veerer/veerer/linear_expression.py:182, in LinearExpression.ppl(self)
    180 from gmpy2 import mpz
    181 import ppl
--> 182 lin = self.integral()
    183 return sum(mpz(coeff) * ppl.Variable(i) for i, coeff in lin._f.items()) + mpz(lin._inhomogeneous_term)

File ~/proj/eskin/veerer/veerer/linear_expression.py:169, in LinearExpression.integral(self)
    167 if self.base_ring() is QQ:
    168     return (self.denominator() * self).change_ring(ZZ)
--> 169 raise ValueError('invalid base ring')
</pre>
</details>

**Comment by videlec** [comment]
> With your sample code I get a ValueError.

Sorry. I will polish the code and the commits tonight! I already performed some profiling and optimizations since my last commit.

**Comment by videlec** [comment]
Looking at the profiler we could optimize the computation `GeometricAutomaton` by
* (12%) improving the computation of the canonical labelling (eg `VeeringTriangulation.best_relabelling()`)
* (6%) making `LinearConstraint.ppl` (which converts sage data to `ppl`) faster
* (3%) improving the construction of `LinearConstraint`
* (1%) avoiding repeated calls to `VeeringTriangulation.dimension()`. More precisely, at every call to `geometric_flips()` involves such a call but the answer is the same for all states and would better be only computed once for the automaton.

**Comment by videlec** [comment]
labri server is off (air conditioning is dead). Maybe it is time to move pages from https://www.labri.fr/perso/vdelecro/ to git hub pages...

**Pull request merged**
