### PR TITLE
Require SageMath to be installed

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@videlec should veerer still support to run without SageMath?

**Comment by videlec** [comment]
Good question. It is doable to have veerer in pure python but also extra work to maintain.

**Comment by saraedum** [comment]
> Good question. It is doable to have veerer in pure python but also extra work to maintain.

I don't think it's worth it. Who would want to use veerer in a context where SageMath is not viable? I mean, it doesn't solve a non-mathematical problem (like cysignals say) and if somebody for some reason wanted to use it from Mathematica or something like that, I guess they could be bothered to also install SageMath somehow. It's a substantial hurdle for sure but unless I am mistaken the possible user community is very small.

**Review by videlec — APPROVED** [review]
Looks good to me. Thanks.

**Pull request merged**
